### ISSUE TITLE
Latest version 3.43.16 not pushed to docker hub?

### ISSUE THREAD

**Issue by m-rossi** [angelnu/docker-ccu#31]
When I execute `sudo ./pull.sh` I receive the error `Error response from daemon: manifest for angelnu/ccu:3.43.16 not found`. Seems like the latest image with the tag has not been pushed to the docker hub?

**Comment by m-rossi** [comment]
Okay, it seems like 3.43.15 is the latest version: https://github.com/eq-3/occu/releases/tag/3.43.15

**Comment by angelnu** [comment]
The dockerfile was trying to download a missing branch from Jens´s OCCU repository: I have added a fix for when the branch is missing.

I also just pushed 3.45.5
