### ISSUE TITLE
Container not reachable after hard power off, Raspi 3B+

### ISSUE THREAD

**Issue by klepptor** [angelnu/docker-ccu#32]
Hi!

Many thx for providing the CCU3 as Docker image!

I successfully used deploy.sh to start the container using this "settings" file, I only changed the REGA_PORT to avoid a conflict with an existing nginx installation.

![grafik](https://user-images.githubusercontent.com/3921511/55427446-51a19280-5587-11e9-8119-38cccbb7e9ce.png)

This setup worked fine until I tried to import a RaspberryMatic backup. The container consumed all CPU and RAM ressources of my Raspi 3 B+ and didn't finish for one hour+. I decided to turn off power.

Now the container isn't reachable any more by port 85 (nor any other).

I already tried undeploy.sh/deploy.sh and manually removed (hopefully) all remaining docker remains, but withot success. The container starts, but isn't reachable.

![ccu](https://user-images.githubusercontent.com/3921511/55426065-27020a80-5584-11e9-990e-3ee84b170edc.PNG)

**Comment by klepptor** [comment]
Seems as if docker binds the container only to the ipv6 adress!?!?!?

**Comment by angelnu** [comment]
Did you remove the docker volume after undeploy.sh? From your screenshot at
![image](https://user-images.githubusercontent.com/4406403/55924538-43cbbd00-5bd8-11e9-91b1-f6c364cf667e.png)
Afterwards a new deploy.sh should bring you back to where you were.

If you try again to restore a backup and it hangs then it is useful to find out what process is the one consuming all the CPU. I did time ago restore a backup myself and it did work but it is not a scenario I test regularly.

**Comment by klepptor** [comment]
I just tried again:

undeploy.sh
docker volume prune
docker container prune
docker image prune
deploy.sh with my modified settings file

No luck! Still no open 0.0.0.0:85 that points to the containers :80 

![grafik](https://user-images.githubusercontent.com/3921511/55991446-9675a980-5caa-11e9-8040-0d7d511a11ef.png)


Maybe it's a docker problem!? I think I read about it somewhere else...

I think I will try a fresh raspbian installation to check...

**Comment by angelnu** [comment]
Is the docker container starting successfully? Can you please post `docker logs ccu ` and  `docker inspect ccu`?

**Comment by klepptor** [comment]
docker logs ccu

![grafik](https://user-images.githubusercontent.com/3921511/56039057-b604e480-5d33-11e9-88aa-0e601396d02b.png)

docker inspect ccu
[inspect_ccu.txt](https://github.com/angelnu/docker-ccu/files/3073346/inspect_ccu.txt)

from the process list:
![grafik](https://user-images.githubusercontent.com/3921511/56039227-13993100-5d34-11e9-9b56-49005610f02c.png)

**Comment by angelnu** [comment]
It is hanging on detecting the type of adapter. This is usually a failed fw update or an older version of the ccu container.

Can you try with the latest version? What type of Homematic Adapter do you have?

 If it still fails then there are some options:
- manually reflash the adapter
- killing the hanging process

**Comment by klepptor** [comment]
Tried with the latest container version on an fresh raspbian image, no luck.

The adapter works fine under raspberrymatic on the same raspi.

I'll give up here and maybe try again in a few months when I have more time again...
