### ISSUE TITLE
Installation of plugins possible?

### ISSUE THREAD

**Issue by m-rossi** [angelnu/docker-ccu#48]
As I am a big HomeKit user I am currently looking at https://github.com/thkl/hap-homematic and I am asking myself: Is it possible to install it with docker-ccu? Does the plugin survives reboots and container updates?

**Comment by angelnu** [comment]
Closing issue since migrated to RaspberryMatic -> see https://github.com/jens-maus/RaspberryMatic/wiki/Docker

RaspberryMatic provides support for plugins and they should survive updates - if not please open an issue there - I will provide support there.

**Comment by m-rossi** [comment]
Ok, thanks for the update and all the work you have done!
